name: Process API Specs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  convert_specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get Dependencies
        run: dart pub get

      - name: Run conversion script
        run: dart run lib/main.dart
